import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "ГОРОСКОПІЯ",
  description: "Generated by create next app",
  icons: {
    icon: "/astrology.png?v=2",
  },
};

export default function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <body>{children}</body>
    </html>
  );
}

