import { Inter, Roboto } from "next/font/google";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "ГОРОСКОПІЯ",
  description: "Generated by create next app",
  icons: {
    icon: '/astrology.png?v=2',
  },
};

export default async function LocaleLayout(props: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const { lang } = props.params;

  return (
    <html lang={lang}>
      <body className={`${inter.variable}`}>
        {props.children}
      </body>
    </html>
  );
}


