import { Inter } from "next/font/google";
import "../../app/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "ГОРОСКОПІЯ",
  description: "Generated by create next app",
  icons: {
    icon: '/astrology.png?v=2',
  },
};

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}

export default function LocaleLayout({ children, params }: LocaleLayoutProps) {
  const { lang } = params;

  return (
    <html lang={lang}>
      <body className={inter.variable}>{children}</body>
    </html>
  );
}
