/* eslint-disable */

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "ГОРОСКОПІЯ",
  description: "Generated by create next app",
  icons: {
    icon: '/astrology.png?v=2',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}