import { Inter, Roboto } from "next/font/google";
import Head from "next/head";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "ГОРОСКОПІЯ",
  description: "Generated by create next app",
  icons: {
    icon: '/astrology.png?v=2',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
       <link rel="icon" href='/astrology.png' />
      </Head>
      <body className={`${inter.variable}`}>
        
        {children}
      </body>
    </html>
  );
}
